### PR TITLE
Update Howler, dev dependencies

### PR DESCRIPTION
**Pull request by GeKorm**
- Update Howler to BREAKING v2.0.4 (strict version)
- Update to webpack v3
- Update tests to be compatible with Howler v2, including shims for window.Audio

I've also updated eslint and the airbnb config, however I haven't used `--fix`; it leads to drastic changes which shouldn't be included in this PR.

Thanks for making this package!

### CODE REVIEW

**Comment by GeKorm** [comment]
Accidentally pushed to the wrong branch, last commit is 93edef25424e1758c112b21fd31e129e0382f06f, coverage is 100%

**Comment by GeKorm** [comment]
Hi @joshwcomeau, I have another PR to add on top of this one that adds support for all Howler v2 methods. I've been using that in production for about 4 months now. Although we don't use many of the methods, it's been without problems so far.

By the way I'm willing to maintain the repo if you don't have time. Thanks!

**Comment by joshwcomeau** [comment]
Ah, shoot! Sorry about that; I must've missed the September PR.

Thanks for the offer of maintenance :) yeah, while I hope to be better than letting a PR sit unreviewed for months at a time, I don't use this package at all in my current projects, and don't have the time to give it the attention it deserves. I'll invite you as a collaborator. If you can send me your NPM username (either here or [by email](mailto: joshwcomeau@gmail.com)), I'll give you publish rights as well.

Sorry again for the delay!

**Comment by joshwcomeau** [comment]
(just making sure I didn't miss an email! Lemme know if I have)

**Comment by brycemonster** [comment]
Did this get published?

**Comment by GeKorm** [comment]
@brycemonster Just did, v2 is up

**Pull request merged**
